<?php
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle('OctopusViewer');

$query = $this->params()->fromQuery();
$title = $query['octopusviewer_title'] ?? '';
unset($query['octopusviewer_title']);
?>

<?php $viewer = $this->octopusViewer()->viewer($query, $title); ?>

<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html')->setAttribute('lang', $this->lang()); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headScript(); ?>
        <style>
            html, body, octopusviewer-viewer { height: 100%; margin: 0; }
        </style>
    </head>
    <body>
        <?php echo $viewer ?>
    </body>
</html>
