<?php foreach ($medias as $media): ?>
    <?php $title = $media->title() ?? $this->translate('[Untitled]') ?>
    <a
        class="octopusviewer-media-selector-element"
        title="<?php echo $this->escapeHtml($title); ?>"
        data-media-id="<?php echo $media->id(); ?>"
        data-octopusviewer-render-url="<?php echo $this->url('site/octopusviewer/default', ['controller' => 'media', 'id' => $media->id(), 'action' => 'render'], [], true); ?>"
        data-octopusviewer-info-url="<?php echo $this->url('site/octopusviewer/default', ['controller' => 'media', 'id' => $media->id(), 'action' => 'info'], [], true); ?>"
    >
        <div class="octopusviewer-thumbnail">
            <?php echo $this->thumbnail($media, 'square'); ?>
        </div>
        <div class="octopusviewer-title">
            <span><?php echo $title; ?></span>
        </div>
    </a>
<?php endforeach; ?>
