<?php
/**
 * @var Omeka\Api\Representation\MediaRepresentation[] $medias
 */
?>
<?php
$defaultMediaTitle = $this->siteSetting('octopusviewer_default_media_title', '') ?: $this->setting('octopusviewer_default_media_title', 'untitled');
if ($defaultMediaTitle === 'no_text') {
    $defaultTitle = '';
} else {
    $defaultTitle = $this->translate('[Untitled]');
}
?>
<?php foreach ($medias as $media): ?>
    <?php
    $displayTitle = $media->displayTitle('');
    $defaultTitleForThisEntry = $defaultMediaTitle === 'filename' ? ($media->source() ?? '') : $defaultTitle;
    $title = $displayTitle !== '' && $displayTitle !== $media->source() ? $displayTitle : $defaultTitleForThisEntry;
    ?>
    <a
        class="octopusviewer-media-selector-element"
        title="<?php echo $this->escapeHtml($title); ?>"
        data-media-id="<?php echo $media->id(); ?>"
        data-octopusviewer-render-url="<?php echo $this->url('site/octopusviewer/default', ['controller' => 'media', 'id' => $media->id(), 'action' => 'render'], [], true); ?>"
        data-octopusviewer-info-url="<?php echo $this->url('site/octopusviewer/default', ['controller' => 'media', 'id' => $media->id(), 'action' => 'info'], [], true); ?>"
    >
        <div class="octopusviewer-thumbnail">
            <?php echo $this->thumbnail($media, 'square'); ?>
        </div>
        <div class="octopusviewer-title">
            <span><?php echo $title; ?></span>
        </div>
    </a>
<?php endforeach; ?>
