<?php if ($media->hasOriginal()): ?>
    <a class="octopusviewer-download" href="<?= $this->url('site/octopusviewer/default', ['controller' => 'media', 'action' => 'download', 'id' => $media->id()], [], true) ?>" download title="<?= $this->escapeHtml($this->translate('Download')) ?>">
        <i class="octopusviewer-icon-download"></i>
        <span><?= $this->translate('Download') ?></span>
    </a>
<?php endif; ?>
