<?php $showDownloadLink = $this->siteSetting('octopusviewer_show_download_link', '') ?: $this->setting('octopusviewer_show_download_link', 'no'); ?>
<?php if ($showDownloadLink === 'yes' && $media->hasOriginal()): ?>
    <a class="octopusviewer-download" href="<?= $media->originalUrl() ?>" download title="<?= $this->escapeHtml($this->translate('Download')) ?>">
        <img src="<?= $this->assetUrl('image/download.png', 'OctopusViewer') ?>" />
    </a>
<?php endif; ?>
