<?php
/**
 * @var string[] $attributes
 */

$this->headLink()->appendStylesheet($this->assetUrl('css/octopusviewer.css', 'OctopusViewer'));
$this->headLink()->appendStylesheet($this->assetUrl('css/octopusviewer-viewer.css', 'OctopusViewer'));
$this->headScript()->appendFile($this->assetUrl('js/octopusviewer-viewer.js', 'OctopusViewer'));
?>
<div class="octopusviewer-media-view">
    <octopusviewer-media-view <?= $this->htmlAttributes($attributes) ?>></octopusviewer-media-view>
</div>
