<?php
/**
 * @var array $query
 */
?>
<?php $showMediaSelector = $this->siteSetting('octopusviewer_show_media_selector', '') ?: $this->setting('octopusviewer_show_media_selector', 'auto'); ?>
<?php $showMediaInfo = $this->siteSetting('octopusviewer_show_media_info', '') ?: $this->setting('octopusviewer_show_media_info', 'always'); ?>
<octopusviewer-viewer
    media-query="<?php echo http_build_query($query); ?>"
    site-slug="<?php echo $this->layout()->site->slug(); ?>"
    show-media-selector="<?= $this->escapeHtml($showMediaSelector) ?>"
    show-media-info="<?= $this->escapeHtml($showMediaInfo) ?>"
>
    <span slot="title"><?php echo $this->escapeHtml($this->params()->fromQuery('octopusviewer_title', '')); ?></span>
</octopusviewer-viewer>
