<?php
/**
 * @var array $query
 * @var string $title
 * @var string[] $attributes
 */

$this->headLink()->appendStylesheet($this->assetUrl('css/octopusviewer.css', 'OctopusViewer'));
$this->headScript()->appendFile($this->assetUrl('js/octopusviewer-viewer.js', 'OctopusViewer'));

?>
<octopusviewer-viewer <?= $this->htmlAttributes($attributes) ?>>
    <?php if (!empty($title)): ?>
        <span slot="title"><?= $this->escapeHtml($title); ?></span>
    <?php endif; ?>
</octopusviewer-viewer>
