<?php
$translate = $this->plugin('translate');
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle('MediaViewer');
?>
<?php $viewer = $this->mediaViewer()->viewer($this->params()->fromQuery()); ?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html')->setAttribute('lang', $this->lang()); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headScript(); ?>
        <style>
            html, body, mediaviewer-viewer { height: 100%; margin: 0; }
        </style>
    </head>
    <body>
        <?php echo $viewer ?>
    </body>
</html>
