<?php foreach ($medias as $media): ?>
    <a
        class="mediaviewer-media-selector-element"
        title="<?php echo $this->escapeHtml($media->displayTitle()); ?>"
        data-media-id="<?php echo $media->id(); ?>"
        data-mediaviewer-render-url="<?php echo $this->url('site/mediaviewer/default', ['controller' => 'media', 'id' => $media->id(), 'action' => 'render'], [], true); ?>"
        data-mediaviewer-info-url="<?php echo $this->url('site/mediaviewer/default', ['controller' => 'media', 'id' => $media->id(), 'action' => 'info'], [], true); ?>"
    >
        <div class="mediaviewer-thumbnail">
            <?php echo $this->thumbnail($media, 'square'); ?>
        </div>
        <div class="mediaviewer-title">
            <span><?php echo $media->displayTitle(); ?></span>
        </div>
    </a>
<?php endforeach; ?>
